### ISSUE TITLE
Plugin not working when ST is closed using " X " button present on the title bar

### ISSUE THREAD

**Issue by gtmsingh** [titoBouzout/SideBarFolders#17]
The does not opens the opened folders when it is closed using the [**x**] button present on the title bar in MacOS (mine is OS X Yosemite) but works as it should be when ST is closed using **CMD+Q**.

**Comment by titoBouzout** [comment]
I believe this bug is unrelated to this package, but related to hot_exit and the like. 

Maybe https://github.com/SublimeTextIssues/Core/issues/64 or
