### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by khornberg** [titoBouzout/SideBarFolders#7]
Would be nice to have the same UI as the project system.

I would like to be able to open a small dialog, maybe it could be integrated I'm not sure, and type in the folder I want to open/goto. Vary similar to the current way one can change projects.

**Comment by greescom** [comment]
Great plugin!

I also think keyboard shortcuts would enhance this plugin immeasurably.

it would be amazing if the folder functionality was added to the command pallet. so ctrl+shift+p then type "folder" to get: load folder, append folder, clear sidebar, open folder, etc. Then open folder would be a searchable list of recent folders.

it's still great using alt+d then arrow keys but feels like it's not integrated properly.

Thanks!

**Comment by titoBouzout** [comment]
This has been added :) thanks to @Jainil
